### ISSUE TITLE
"An error occurred. Start over" during rendering phase

### ISSUE THREAD

**Issue by nazincubeta** [google-marketing-solutions/vigenair#10]
We're getting a lot of "An error occured. Start over" messages a lot during the render phase.

It seems to take much longer to render now than the version a few weeks ago, and more often than not, it ends up with this.

It seems to happen more often with videos over 2 minutes long, and also when doing a queue with multiple variants.

Is there a way to monitor the render status via logs or something?

Anything we can do to mitigate this render error (crash?)?

**Comment by mohabfekry** [comment]
That's expected because we've added proper rendering of vertical and square formats. Either uncheck that checkbox for your variants or increase your Cloud Functions memory and vCPU settings (from the default 8,2 to 16,4 or 32,8 respectively).

**Comment by nazincubeta** [comment]
I'm not actually sure if it's during the rendering phase or the "Loading rendered videos" phase.

I get to the "loading rendered videos" with the loading spinner and it also errors out there

**Comment by mohabfekry** [comment]
I've added more details in my comment, please check.

**Comment by nazincubeta** [comment]
Can you describe more what the 6000ms delay and 100 iterations here do, so I'll know how to tweak them?

getFromGcs(`${folder}/input.vtt`, 'text/vtt', 6000, 100)

Thank you!

**Comment by mohabfekry** [comment]
Apologies, I copied the wrong line; the correct line you'd need to change is L389 (in the `getRenderedCombos` method):
 https://github.com/google-marketing-solutions/vigenair/blob/main/ui/src/ui/src/app/app.component.ts#L389

The system will retry every 6000ms (6s) for 100 times to "read" the results of the rendering from Cloud Storage. (6s*100= 10 minutes).

Either increase the delay or the iterations to give the app more time to wait for rendering.
