### ISSUE TITLE
Stuck in Video Editing screen 

### ISSUE THREAD

**Issue by gazly** [google-marketing-solutions/vigenair#13]
Thank you based on your suggestions and after OAuth configurations application is loading via Appscript

But the site is stuck here-- tried with many videos

Content language is not English, is it a concern?
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/6efb48a3-9a70-4eb0-bf9b-1ad6582dc97c">

I checked the bucket, file is available there
<img width="1040" alt="image" src="https://github.com/user-attachments/assets/b6e804a2-7316-4689-a76c-be745ee9328c">

**Comment by mohabfekry** [comment]
Navigate to Cloud Functions and open the "vigenair" cloud function and go the logs view and scroll down to refresh it. Check if there are errors there, and if so, please share so I can assist you further.

**Comment by gazly** [comment]
I just redeployed with the new git and it works like a charm! 
Thank you for the wonderful tool <3 
Keep building!
