### ISSUE TITLE
 UI Web App Link does not work

### ISSUE THREAD

**Issue by fabnoe** [google-marketing-solutions/vigenair#14]
Installation process was successful but:

IMPORTANT ->: https://script.google.com/a/macros/google.com/s/AKfyc....
**Link does not work: Page cannot be opened...**

**Comment by mohabfekry** [comment]
Are you accessing the app with the same Google account you deployed it with? (please try in a private / incognito window)
Also, have you enabled the Apps Script API as mentioned in step 3 of https://github.com/google-marketing-solutions/vigenair#get-started ?

**Comment by fabnoe** [comment]
I followed all of the steps above, same error. Could there be an issue because I am trying to open the url from Europe while everything was deployed for US? 

https://script.google.com/a/macros/google.com/s/AKfycbzOme1oRcTLN-AfKnVJet3l2JSXO8YOnW98rs7zMiMH7bsMPL1nkKu5HkSVinAoL2BO6g/exec
johnedoe@OnAMac12345

**Comment by mohabfekry** [comment]
No, where the backend cloud function is deployed does not influence where the UI web app is accessible from.

Perhaps the link you're using is outdated?
You might try to access the app via the Apps Script home page instead as described here: https://github.com/google-marketing-solutions/vigenair#managing-apps-script-deployments
