### ISSUE TITLE
UI breaks after upload - 404 (Not Found)

### ISSUE THREAD

**Issue by fabnoe** [google-marketing-solutions/vigenair#15]
Browser console outputs after video selection:

> Upload complete! {kind: 'storage#object', id: 'vigenair-test-02827 …}
>         
>  **GET** https://storage.googleapis.com/storage/v1/b/vigenair-test-434419-vigenair/o/eharmony%20_%20Get%20Who%20Gets%20You%202023.mp4--1725306798321--ZmFiaWFuLm5vZXRoZUBnbWFpbC5jb20%3D%2Finput.vtt?alt=media **404 (Not Found)**
> Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).

**Comment by mohabfekry** [comment]
Seems like you might have not followed the "Requirements" section of the readme. Particularly:

"All users running Vigenair must be granted the Vertex AI User and the Storage Object User roles on the associated GCP project".

**Comment by fabnoe** [comment]
Not sure what's missing:
<img width="879" alt="image" src="https://github.com/user-attachments/assets/460a7e78-1175-4488-99ed-0619840ca836">

**Comment by mohabfekry** [comment]
Your user account needs these roles not the default compute service account (we automatically set the correct roles for that as part of the deployment).

I do (slightly) see however that your account @gmail.com has Owner - is that the account you're using to access the app? Owner should of course implicitly have Storage Object User and Vertex AI User, unless you're accessing the app with a different account that does not have these roles.

**Comment by fabnoe** [comment]
@mohabfekry  Yes, I am using my @gmail to access the UI. This is what the permissions look like for my account. I have also done the authorisation with this account. Sorry, maybe I misunderstood the docs but it's not working here.

<img width="991" alt="image" src="https://github.com/user-attachments/assets/92647a84-a788-47e4-a2ea-e58db9e9888e">

**Comment by mohabfekry** [comment]
Do you have popups blocked on the web app in your browser?

The app would prompt you to authenticate to Google Cloud when you open it and try to access files from Cloud Storage for the very first time. Perhaps this is blocked so you're being treated as not authenticated.

From a cloud access point of view it seems like everything is correct already (as I mentioned earlier, Owner is sufficient).

You may also try accessing the web app in a private / incognito window where you'd be forced to relogin and reauthenticate.

**Comment by fabnoe** [comment]
@mohabfekry Okay, there is no pop-up to "authenticate to Google Cloud". This seems to be the problem. 
I just tried to pause AdBlocker, useed incognito window, but there is no pop-up. Same error, I am sorry.

**Comment by fabnoe** [comment]
@mohabfekry  Any final ideas how to get this running?

**Comment by mohabfekry** [comment]
As mentioned before, this issue only affects you and is not reproducible by neither anyone who uses the tool nor by our team. You must have missed a step or broken something in Cloud permissions 

You can try to `git reset --hard` or completely remove your workspace and install the app in a fresh GCP project and a fresh Apps Script project (you'd need to remove any traces of .clasp*.json files from your workspace). I can't say if that would help as I can't pinpoint what the issue you are currently experiencing is to begin with.

**Comment by fabnoe** [comment]
@mohabfekry  Thanks for the advice. I removed everything, followed the readme step by step. Seems like I am overlooking something all the time.

Can you you help me with this Cloud Permissions for my user on the Vigenair Project. This is my setup for Google Cloud IAM for my Vigenair Project. 

<img width="278" alt="image" src="https://github.com/user-attachments/assets/dbb62f49-b8ce-4806-a311-bbecdf9629bf">
