### ISSUE TITLE
Internal Vigenair solution not woriking 

### ISSUE THREAD

**Issue by marianags88** [google-marketing-solutions/vigenair#17]
Hi team,
Hope you are doing great, 

Can you help me out reviewing if we have a bug on the internal vigenair accounts because we have the same error: 
https://screenshot.googleplex.com/6cnA5EeXWiCPjbJ.png
We are trying to pitch the solution with real examples but we've been having this issue since last week, 09/09

Best

**Comment by mohabfekry** [comment]
Ping us internally (go/ask-vigenair) - this is a public repo :)
It seems to me that you don't have storage access to your GCP instance, or you've deployed the frontend with incorrect values in `ui/src/config.ts`.  You might have had the issue listed in this note on https://github.com/google-marketing-solutions/vigenair#get-started :

> Note: If you have already run the script and you notice that there was a typo in one of the inputs, or if you would like to change the Cloud region, GCS location, or the UI access settings for Google Workspace users, you must first run git reset --hard before rerunning npm start.
