### ISSUE TITLE
Uploaded Video Not Processed: Always Using Default Video

### ISSUE THREAD

**Issue by kng246** [google-marketing-solutions/vigenair#2]
When attempting to run the app locally on my browser, the uploaded video is not being considered for processing. Instead, the application always uses the default video, regardless of the video file uploaded by the user.

https://github.com/google-marketing-solutions/vigenair/assets/89521555/4aa88908-a29f-4c85-ae2c-6853ae6abede

**Steps to Reproduce**

1. Clone the repository.
2. Navigate to the project directory.
3. cd ui
4. npm run serve-ui
5. open `http://localhost:4200/`

**Comment by mohabfekry** [comment]
Thanks for opening the issue. This is works as designed; serving the app locally only works with the default assets as it is only meant for dev purposes when contributing to the UI component.

If you'd like to upload a video, please use the Apps Script deployed version of the app. Check https://github.com/google-marketing-solutions/vigenair?tab=readme-ov-file#managing-apps-script-deployments for more info
