### ISSUE TITLE
Not able to render shorter variant for a vertical creative

### ISSUE THREAD

**Issue by Sahil45745** [google-marketing-solutions/vigenair#24]
Hi Team,
The solution not able to render a shorter version of a vertical base video. Please look into it and help in resolving the issue 
Thanks in advance!

**Comment by mohabfekry** [comment]
Please provide more information. Have you checked the Cloud Function logs, are there errors? Or is the application failing within the UI stage already?

**Comment by Sahil45745** [comment]
Hi Mohab,

Thanks for the prompt response. The application is failing within the UI.
After clicking on the render button, the processing isn't ending. It is
working fine for a landscape video.

Thanks,
Sahil

**Comment by mohabfekry** [comment]
Thanks for the additional information, that was quite helpful. We identified an issue which will be fixed very soon.

**Comment by Sahil45745** [comment]
Thanks Mohab. Looking forward to it!
