### ISSUE TITLE
userCodeAppPanel:1669                           GET https://storage.googleapis.com/storage/v1/b/pfg-ai-vigenair/o/24_10_UP_Monatsvideo_30Sek_16zu9.mp4--n--1729165400549--ZG9taW5pcXVlLmx1ZWJiZW5AcG9wa2VuLXNlcnZpY2VzLmRl%2Finput.vtt?alt=media 404 (Not Found)

### ISSUE THREAD

**Issue by DominiqueLuebben** [google-marketing-solutions/vigenair#26]
![Error](https://github.com/user-attachments/assets/ecdd90bc-0f8a-4a4e-827b-61e9f2e3a78d)
directly after the upload, an error occours that the uploaded video can't be accessed/get from cloud storage. You can even load the prior uploaded video in "video selection" and still get the same error.

**Comment by DominiqueLuebben** [comment]
I got further information. The problem is that the function tries to get a .vtt file that is not created or uploaded to the storage. The same goes for the different analysis steps and there file types.

**Comment by mohabfekry** [comment]
Please read the README. The UI waits until the files are processed by the Cloud Function and available in Cloud Storage, so the 404s here are expected.

**Comment by DominiqueLuebben** [comment]
I know that. The cloud functions are never opened by your script and I have been timed out several times.

**Comment by mohabfekry** [comment]
We enhanced the error logging with https://github.com/google-marketing-solutions/vigenair/commit/e9524c0634bd9af50696d626b51584790d543624 so you shouldn't see any other errors in the console except the 404s - which are again expected as long as your video hasn't processed yet and is not yet available on GCS.

**Comment by fabnoe** [comment]
@mohabfekry  Same error here.

But how do I know when this process is complete...or how do I check if it's running at all?
_"video hasn't processed yet and is not yet available on GCS"_
