### ISSUE TITLE
Video not being split into segments - function looping with no script 

### ISSUE THREAD

**Issue by richclogg** [google-marketing-solutions/vigenair#27]
Hi, is it possible to supply a demo video that has been tested on Vigenair. I have app working but nothing gets split when I upload the video. The function generateVariants just loops as there are no segments and hence no video scripts

**Comment by mohabfekry** [comment]
Please make sure you're on the latest version of the application - we've done several improvements to the UI error handling so that you don't get "stuck" in a loop. Always also check the browser logs for additional information on what might be the error, and post here should the problem persist after deploying the latest verison.

**Comment by richclogg** [comment]
Thank you. I have updated my repo and rerun npm start. The script is hanging at creating service agents and granting roles. It gives me a menu but whatever I choose it keeps looping back. Is there a flag or something I need to do to skip this step as its a re-install? INFO - Creating Service Agents and granting roles...
 [1] EXPRESSION=request.time < timestamp("2024-10-25T09:35:59.055Z"), TITLE=cloudbuild-connection-setup
 [2] None
 [3] Specify a new condition
The policy contains bindings with conditions, so specifying a condition is required when adding a binding. Please specify a condition.:

**Comment by richclogg** [comment]
Yes, I saw that, thanks. However, I am still getting stuck at this step. [1] EXPRESSION=request.time < timestamp("2024-10-25T09:35:59.055Z"), TITLE=cloudbuild-connection-setup
[2] None
[3] Specify a new condition
The policy contains bindings with conditions, so specifying a condition is required when adding a binding. Please specify a condition.:

**Comment by mohabfekry** [comment]
Could you please check (e.g. via git) changes in your local version of https://github.com/google-marketing-solutions/vigenair/blob/main/ui/src/config.ts and make sure the only changes you have in there are the values for:
- `cloudStorage.bucket`
- `vertexAi.projectId`
- `vertexAi.location`
?

It looks like you might have overriden parts of this file, perhaps by mistake.
If not, then you'd just need to try "Generate Variants" again. 

The response from Gemini that you sent above indicates that the "video script" that we compile with all information we've extracted from the video (see https://github.com/google-marketing-solutions/vigenair#41-variants-generation) is not being passed in the prompt to Gemini, which is leading me to think that the file above (which contains the prompt) has been changed erroneously.

If not, then it's just a Gemini glitch and you'd just have to try generating variants for your video again.

Finally, here's an example of a video that I've personally run through the app multiple times: https://www.youtube.com/watch?v=0b2_Kzh6Ia4

**Comment by richclogg** [comment]
> Could you please check (e.g. via git) changes in your local version of https://github.com/google-marketing-solutions/vigenair/blob/main/ui/src/config.ts and make sure the only changes you have in there are the values for:
> 
> * `cloudStorage.bucket`
> * `vertexAi.projectId`
> * `vertexAi.location`
>   ?
> 
> It looks like you might have overriden parts of this file, perhaps by mistake. If not, then you'd just need to try "Generate Variants" again.
> 
> The response from Gemini that you sent above indicates that the "video script" that we compile with all information we've extracted from the video (see https://github.com/google-marketing-solutions/vigenair#41-variants-generation) is not being passed in the prompt to Gemini, which is leading me to think that the file above (which contains the prompt) has been changed erroneously.
> 
> If not, then it's just a Gemini glitch and you'd just have to try generating variants for your video again.
> 
> Finally, here's an example of a video that I've personally run through the app multiple times: https://www.youtube.com/watch?v=0b2_Kzh6Ia4

Thanks Mohab. All those files are unchanged. How do I get the mp4 version of this video? Seems its not an option even with YT premium?
