### ISSUE TITLE
Cloud Build in service deploy - question not issue

### ISSUE THREAD

**Issue by richclogg** [google-marketing-solutions/vigenair#29]
Hi, this is a question vs an issue. I am following the install process for the services portion of the app. When i look through the deploy.sh, i see the gcloud command ot create the function, but where does it create a cloud build for it and where does it reference/create the source code (function-source.zip) in the GCS bucket? It just seems that that part of the build is missing in the build script code (it obviously isn't )

Thanks in advance!

**Comment by mohabfekry** [comment]
https://github.com/google-marketing-solutions/vigenair/blob/main/service/deploy.sh#L91

Specifying the source directory as the current directory tells Cloud Functions to take all of the code in said directory, zip it and use it as the function source. This has the benefit that when you click "Edit source code" in the UI you can see the same set of files in the same folder hierarchy as you would in the local file system.
