### ISSUE TITLE
Error during npm start

### ISSUE THREAD

**Issue by afonsomv** [google-marketing-solutions/vigenair#30]
Hello! 

During the step 7 ("npm start") I've encountered some errors in the CLI:

![image](https://github.com/user-attachments/assets/8bf25bb4-48db-4103-bea8-7603abeb0882)

Can someone help me with these?

**Comment by afonsomv** [comment]
I've also encountered multiple errors regarding gcloud: "gcloud: command not found"

![image](https://github.com/user-attachments/assets/3e86f01d-aaa2-4c02-9219-80d61381b15d)

What does this mean? I've installed the gcloud CLI and even made the auth login

**Comment by mohabfekry** [comment]
You must have installed gcloud for a different user. Please make sure it's installed and globally accessible (you might need to `sudo` before it as mentioned in https://cloud.google.com/sdk/docs/install).

With regards to the TS error, that's a minor regression issue that we'll solve very soon. Thanks for reporting it.

**Comment by afonsomv** [comment]
Thanks for the help! 

When you mean `sudo` install, do you mean right before `./google-cloud-sdk/install.sh`? Where is this explained in the documentation you've mentioned? (I couldn't found it).

Thank you again!!

**Comment by afonsomv** [comment]
Thank you! I've already solved this!
