### ISSUE TITLE
Web App constantly "Loading video segments"

### ISSUE THREAD

**Issue by afonsomv** [google-marketing-solutions/vigenair#31]
Hello! 

Another issue occurred to me: The UI seems to always be in this step. Is it normal? I also haven't seen the cloud function / cloud run in my google cloud project, could it be related to that?. 

But the installation seemed to be finished and I was able to get the web app link. 

Is it normal to be constantly "Loading video segments"? 

Thank you in advance

![image](https://github.com/user-attachments/assets/8ed183f9-e8b2-45c4-a5ee-e402ab5e63e7)

**Comment by mohabfekry** [comment]
I think this is related to your other issue, where the cloud deployment didn't work because of the missing "gcloud" cli. 

Please rerun ./service/deploy.sh and make sure - after the deployment is successful - that you're able to see a `vigenair` cloud function in your GCP project.

**Comment by afonsomv** [comment]
It actually had to do with the location I specified. I've been able to fix the "gcloud" issue earlier in the day. But there was an inconsistency in the way I specified the locations during the npm start and gcloud installation. 

Thank you anyway!
