### ISSUE TITLE
Authorization flow for Clasp does not redirect to cloud shell

### ISSUE THREAD

**Issue by maximilianw-google** [google-marketing-solutions/vigenair#4]
Acutal behavior: When reach clasp login step auth flow does not continue in cloud shell but redirects to localhost.

<img width="1628" alt="image" src="https://github.com/google-marketing-solutions/vigenair/assets/53622210/3e245af6-136d-4ec6-9c1f-e9ab6d3a4f46">

Expected behavior: After logging in with a google account, clasp login flow continues in cloud shell.

**Comment by mohabfekry** [comment]
The out of band flow for GCP auth is deprecated, so you need to run this as a user on your "local" machine. This is unfortunately WAI.
