### ISSUE TITLE
Not able to editing the video or preview the segments

### ISSUE THREAD

**Issue by rtong02** [google-marketing-solutions/vigenair#6]
I have deployed the UI to App Script and uploaded the default video. It didn't allow me to editing the video or preview them.
<img width="955" alt="image" src="https://github.com/user-attachments/assets/454b9d40-7380-422f-bd69-03909b175346">

**Comment by mohabfekry** [comment]
Have you also deployed the Cloud components? You obviously need that as well to upload and process videos.

If you'd just like to test the frontend you can navigate to the Angular source folder (`<root>/ui/src/ui`) and run `ng serve`.

**Comment by rtong02** [comment]
I deployed all cloud components in GCP.
